controllers:
  - unit: 1
    type: ttsync5
    devices:
      1: Riing Plus
      2: Riing Plus
      3: Riing Plus
      4: Riing Plus
      5: Riing Plus

fan_managers:
  - setting: back
    devices: {1: [3, 4]}
    model: curve
    points:
      - [0, 0]
      - [40, 30]
      - [60, 80]
      - [70, 100]
    sensor_name: coretemp

  - setting: top
    devices: {1: [1, 2]}
    model: temp_target
    target: 40
    multiplier: 5

  - setting: default
    model: locked_speed
    speed: 50

lighting_manager:
  - setting: bellow
    devices: {1: [4, 5]}
    model: wave
    speed: extreme
    grb: [40, 40, 0]
    grbs: [[40, 0, 0], [30, 10, 0], [20, 20, 0], [10, 30, 0], [0, 40, 0], [0, 30, 10], [0, 20, 20], [0, 10, 30], [0, 0, 40], [10, 0, 30], [20, 0, 20], [30, 0, 10]]

  - setting: default
    model: thermal
    cold: 30
    hot: 65
    target: 45
    sensor_name: coretemp

